name: My First workflow 

on: push 

jobs: 
    first_job: 
        runs-on: unbuntu-latest
        steps:
        - name: Welcome Message 
          run: echo "My first Github actions job"

        - name: List files 
          run: ls 
        
        - name: Read file 
          run: cat README.md
