name: Generate ASCII Artwork
on: 
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y 
      

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - run: mkdir -p .github/workflows/job-3.yaml
      - run: touch cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      - run: ls -la
      - uses: actions/upload-artifact@v7
        with:
          path: .github/workflows/job-3.yaml/dragon.txt
          archive: false

   #god did      
  test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file 
        uses: actions/download-artifact@v8
        with:
          name: dragon.txt

      - name: Test file exists 
        run: cat dragon.txt
        
  deploy_job_3:
      needs: [test_job_2]
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file 
        uses: actions/download-artifact@v8
        with:
          name: dragon.txt

      - name: Deloy 
        run: echo Deploying ... .. . 