name: Exploring Variables and Secrets 

on: 
    push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: docker build -t docker.io/dockerUsername/imageName:latest 

    - name: Docker Login
      run: docker login --username=docjerUsername --password=s3cUrePaSsw0rd 

    - name: Docker Publish
      run: docker push docker.io/dockerUsername/imageName:latest

  deploy:
    needs: docker 
    runs-on: ubuntu-latest 
    steps:
    - name: Docker Run 
      run: docker run -d -p 8000:80 docker.io/dockerUsername/imageName:latest

      ################# variable step level ###############################################################################


  docker7: 
    runs-on: ubuntu-latest 
    steps:
    - name: Docker Build
      env:
        CONTAINER_REGISTRY: docker.io 
        DOCKER_USERNAME: itcouldofbeen103
        IMAGE_NAME: github-actions-nginx
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 
## docker build is using $ to rep the variables to be entered on the build 
## on the env you can auto fill the evn then use double {} 

    - name: Docker Login 
      env: 
        DOCKER_PASSWORD: s3cUrePaSsw0rd
        DOCKER_USERNAME: itcouldofbeen103
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Docker Publish 
      env: 
        CONTAINER_REGISTRY: docker.io 
        DOCKER_USERNAME: itcouldofbeen103
        IMAGE_NAME: github-actions-nginx
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 
## for the password you want it in secrets 

  deploy11:
    needs: docker 
    runs-on: ubuntu-latest 
    steps:
    - name: docker run 
      env: 
        CONTAINER_REGISTRY: docker.io 
        DOCKER_USERNAME: itcouldofbeen103
        IMAGE_NAME: github-actions-nginx
      run: echo docker -d -p 8000:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

#### define at the job level so users do not repeat same commands    ##############################################################
##putting it at the job level makes it avaliable on all 3 
    
  docker1:
    env: 
        CONTAINER_REGISTRY: docker.io 
        DOCKER_USERNAME: itcouldofbeen103
        IMAGE_NAME: github-actions-nginx
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Build 
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

    - name: Docker Login 
      env: 
        DOCKER_PASSWORD: s3cUrePaSsw0rd
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
#### only use the docker password on the login level thats why its not on the job and env variables are put at the job level to reduce redundency 
    
    - name: Docker Publish 
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 


  deploy1:
    needs: docker 
    env: 
        CONTAINER_REGISTRY: docker.io 
        DOCKER_USERNAME: itcouldofbeen103
        IMAGE_NAME: github-actions-nginx
    runs-on: ubuntu-latest 
    steps:
    - name: docker run 
      run: echo docker -d -p 8000:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

####### worker level  varaiable ######################
    

name: Exploring Variables and Secerts

on1:
  push


env: 
    CONTAINER_REGISTRY: docker.io 
    DOCKER_USERNAME: itcouldofbeen103
    IMAGE_NAME: github-actions-nginx

job:
  docker: 
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Build 
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

    - name: Docker Login 
      env: 
        DOCKER_PASSWORD: s3cUrePaSsw0rd
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
#### only use the docker password on the login level thats why its not on the job and env variables are put at the job level to reduce redundency 
    
    - name: Docker Publish 
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 


  deploy:
    needs: docker   
    runs-on: ubuntu-latest 
    steps:
    - name: docker run 
      run: echo docker -d -p 8000:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME


    