name: Vault Demo 

on:
  workflow_dispatch:

jobs:
    echo-vault-secret:
      runs-on: ubuntu-latest
      steps:
      - name: Testing Secrets
        run: | 
          if [[ -z "$(( secrets.AWS_API_KEY ))"]]; then
             echo "Secret Not found"
             exit 1 
          else 
            echo "Secret Found"
            exit 0
          fi 


 ## HOW TO USE HASHICORP VAULT cloud FOR SECRETS
# THE PROBLEM WITH SECRETS BEING STORED ?
# when using storing secrets in repos/environment levels on mulitple repos , github does not have secret versioning 
                # WHAT DOES THAT MEAN ?
# github stores the secrets per repo resulting in duplicate secrets across different repos
# so inconsistencies between environments can merge if secret values in the github actions deployment environment are different 
                # SOLUTION ##
# in order to avoid duplicate secrets use hashicorp vault it manages the sccrets centrally and it enables syncing between mulitple repos we
# developers can access the secrets by syncing them into hashicorp vault directly

# WORKFLOW HOW TO READ IT 
# 1. on: workflow dispatch is a manually triggered action 
# 2. it has 1 job with 1 step 
# 3. checks if the aws secret is accessible or not empty 
# 4. the if statements represent if the secret is found or not with echos and exit 1 or 0
# 5. commit and then manually go to the actions >> tigger workflow >> it will fail meaning exit 1 
